# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('number', models.CharField(max_length=200, verbose_name='Numero')),
                ('status', models.CharField(choices=[('created', 'Criada'), ('started', 'Iniciada'), ('stoped', 'Pausada'), ('finished', 'Terminada')], default='created', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Desk',
                'verbose_name_plural': 'Desks',
            },
        ),
    ]
