# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'Criada'), ('started', 'Iniciada'), ('stoped', 'Pausada'), ('finished', 'Terminada')], default='created', max_length=20, verbose_name='Status'),
        ),
    ]
