# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_auto_20161022_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='next_desk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='desk.Desk', verbose_name='Mesa Seguinte'),
        ),
        migrations.AddField(
            model_name='desk',
            name='previous_desk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='desk.Desk', verbose_name='Mesa Anterior'),
        ),
    ]
