# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='In\xedcio')),
                ('end', models.DateField(verbose_name='Fim')),
                ('order_desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='order.OrderDesk')),
            ],
            options={
                'verbose_name': 'Order Desk History',
                'verbose_name_plural': 'Order Desk History',
            },
        ),
    ]
