# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20161022_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='history',
            name='start',
            field=models.DateTimeField(verbose_name='In\xedcio'),
        ),
    ]
