# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desk', '0002_auto_20161022_0817'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('deadline', models.IntegerField(verbose_name='Prazo (dias)')),
                ('status', models.CharField(blank=True, choices=[('created', 'Criada'), ('started', 'Iniciada'), ('stoped', 'Pausada'), ('finished', 'Terminada')], default='created', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_desks', to='desk.Desk')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_desks', to='order.Order')),
            ],
            options={
                'verbose_name': 'Order Desk',
                'verbose_name_plural': 'Order Desks',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='desks',
            field=models.ManyToManyField(blank=True, related_name='orders', through='order.OrderDesk', to='desk.Desk'),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='item.Item'),
        ),
    ]
