# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_items_produced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_produced',
            field=models.IntegerField(verbose_name='Itens produzidos'),
        ),
    ]
