# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20161023_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_produced',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
