# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20161023_0139'),
        ('order', '0003_auto_20161023_1712'),
    ]

    operations = [
    ]
