# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_merge_20161023_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='damage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Preju\xedzo'),
        ),
    ]
