# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20161023_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='damage',
            new_name='loss',
        ),
    ]
