# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20161023_1711'),
        ('order', '0005_merge_20161023_1827'),
    ]

    operations = [
    ]
