# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_merge_20161023_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='loss',
            field=models.IntegerField(blank=True, null=True, verbose_name='Preju\xedzo'),
        ),
    ]
