# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0007_auto_20161023_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(verbose_name='Hora')),
                ('produced', models.IntegerField(verbose_name='Pe\xe7as produzidas')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='order.Order')),
            ],
            options={
                'verbose_name': 'Order Desk History',
                'verbose_name_plural': 'Order Desk History',
            },
        ),
    ]
